### PR TITLE
Adds scala-tutorial Library

### LINKED ISSUE #603: Scala Exercises based off of MOOC curriculum
Hi guys,

I'm not sure if this is the right place to be posting this as this is a content-related point rather than a technical one. So feel free to close/move it if it should be somewhere else.

But in continuing to work on the Scala MOOCs, I just realized that I would love to point people to scala-exercises.com from the MOOC videos and resource pages. In particular for the Spark course, because we expect that people will skip over the previous 3 MOOCs introducing Scala + the fundamentals, just being in a rush to learn Spark.

So I started looking around for something interactive that I could point people at. I immediately thought of scala-exercises, but realized that the stdlib exercises is maybe not the best place to point these people. Not that there's anything wrong with it, it's just maybe not the best beginner-first place to send people trying to get a quick idea of what Scala is all about. 

That said, I was thinking it would be cool if there was a set of exercises based on the first 2 MOOCs (Functional Programming Principles in Scala and Functional Program Design in Scala). The progression that Martin has designed for these courses is really spot on, if you ask me (of course I'm biased). 

Just brainstorming here. Would something like this ever be feasible? (Again, just trying to figure out what I should point fast-track students at)

### PR DESCRIPTION
**Pull request by juanpedromoreno**
**DO NOT MERGE YET**

Fixes #603 and #616

### CODE REVIEW

**Comment by juanpedromoreno** [comment]
Hi @julienrf, I've deployed in this stage env the new library. Everything looks good, however, I can see how in the first chapter, in the second exercise, the expected types are interchanged:

https://scala-exercises-pr-617.herokuapp.com/scala_tutorial/terms_and_types

Please, correct me if I'm missing something. Thanks.

**Comment by julienrf** [comment]
Oh, good catch! Indeed, it seems that I can not use `res1` *before* using `res0`, here: https://github.com/scala-exercises/exercises-scalatutorial/blob/master/src/main/scala/scalatutorial/sections/TermsAndTypes.scala#L123-L124

It might be an issue of scala-exercise?

Anyway, I’ll fix the exercise definition by swapping the arguments order.

**Comment by julienrf** [comment]
So, I went through all the other exercises and they are fine, excepted that we can not run an exercise that takes no parameters. I have an exercise that does not take parameters (ie. where users have nothing to fill in) in order to show the output of the compilation. Also, sometimes I don’t end a section with an exercise, so I put a dummy function instead, but this function is not runnable from the UI.

Do you think it would be possible to make these no-args functions runnable from the UI?

**Comment by julienrf** [comment]
BTW, I just pushed [this commit](https://github.com/scala-exercises/exercises-scalatutorial/commit/fed99499f32737d1327ff8b06ad405210ff6e4dc) to the scalatutorial repo.

**Comment by juanpedromoreno** [comment]
It might be possible if we modify the UI, activating the `Run` button for those exercises that contains code but don't have any exercise.

**Comment by julienrf** [comment]
@juanpedromoreno I’m not sure it will be enough: these disabled exercises must also not be taken into account by the progress bar:

progress

**Comment by juanpedromoreno** [comment]
Right @julienrf That's an issue.

**Comment by juanpedromoreno** [comment]
Closing and creating a new PR in order to re-deploy Heroku.

https://github.com/scala-exercises/scala-exercises/pull/618

**Comment by juanpedromoreno** [comment]
I've submitted the issue: https://github.com/scala-exercises/scala-exercises/issues/619

**Pull request closed without merging**
