### PR TITLE
Implement Evaluator based on Scala Compiler

### PR DESCRIPTION
**Pull request by MasseGuillaume**
* Evaluator produce an EvalResult[T] it has more information than the original EvaluationResult[T]
  double check to see what can be bubble back to the ui
    * RangePosition in CompilationInfo would need to be shifted (see wrapedCode in eval[T])
* I'm using sbt BuildInfo in ExerciceService to find the correct classpath (artifacts). This would changed when deployed.
  I'm not too familiar with Play dependency injection, it's up to you guys to figure it out.
* MethodEval security (jvm SecurityManager) is off by default in ExercisesService. Play and sbt are running on the same jvm. It should work fine when deployed.

### CODE REVIEW

**Comment by raulraja** [comment]
@MasseGuillaume Great stuff. I'll defer to @andyscott review of this PR given he had spent the most time around the evaluation code prior to this change.

**Comment by MasseGuillaume** [comment]
@andyscott ping ?

**Comment by dialelo** [comment]
It seems like the build failed due to an [unresolved dependency](https://travis-ci.org/scala-exercises/scala-exercises/builds/131005108#L1958), can you take a look @MasseGuillaume ?

**Comment by MasseGuillaume** [comment]
@dialelo I solved the issue with the `runtime-example` resolution. Now it's something else: https://travis-ci.org/scala-exercises/scala-exercises/builds/132277148#L1089

**Comment by MasseGuillaume** [comment]
@dialelo done ;-)

**Comment by dialelo** [comment]
We may want to review the error messages in the future but this is awesome!

timeout

I've tested it locally and works perfectly, LGTM :shipit:

**Comment by dialelo** [comment]
Hmm, it seems like it doesn't find some imports. In the `Apply` section of cats we are importing an object defined in the same package called `ApplyHelper` but is not available when evaluating the code:

notfoundimport

**Comment by dialelo** [comment]
Same problem for every section that imports an object defined on its own package, any ideas about what can be failing @MasseGuillaume? We can work around it including all the code in the section file but is less than ideal.

**Comment by MasseGuillaume** [comment]
@dialelo I'm checking this out ;-)

**Comment by dialelo** [comment]
Awesome :sparkles:

**Comment by MasseGuillaume** [comment]
An import is missing from the Exercice plugin

This is the generated code:
```
import cats.syntax.cartesian._
import cats.syntax.apply._
import cats.std.all._
import cats._
import ApplyHelpers._
import org.scalatest._
class Eval2803112120684302132 extends (() ⇒ Any) {
  def apply() = catslib.ApplySection.applyExtendsFunctor(Option("1"), Option(2), None)
}
```

it's missing `package catslib` or `import catslib._`

**Comment by dialelo** [comment]
@MasseGuillaume can you review and merge [my PR to your master branch](https://github.com/MasseGuillaume/scala-exercises/pull/1) so it is included in this PR, please? Thanks in advance!

**Comment by MasseGuillaume** [comment]
@dialelo tested locally with your PR works perfectly. Thanks!

**Comment by dialelo** [comment]
@rafaparadela @raulraja @andyscott please take a look and let us know if you run into any problems. If not I think this is good to merge.

**Comment by andyscott** [comment]
I will make time to look at this ASAP. Sorry for the delay guys.

**Comment by MasseGuillaume** [comment]
Also, I took some bits from Twitter Eval
https://github.com/twitter/util/blob/develop/util-eval/src/main/scala/com/twitter/util/Eval.scala#L74-L86
https://github.com/twitter/util/blob/develop/util-eval/src/main/scala/com/twitter/util/Eval.scala#L319-L365
It's to extract useful Path from the classpath.

It's an Apache 2.0 so it's compatible. We need to comply with the [Redistribution section](https://github.com/twitter/util/blob/develop/LICENSE#L90-L129)

**Pull request merged**
