### PR TITLE
Move src/main/exercises to src/main/scala

### LINKED ISSUE #303: Move exercises to src/main/scala
Looks like neither Ensime nor IntelliJ is able to find exercises as valid Scala sources when placed in `src/main/exercises`. Furthermore Scalariform is not getting applied to those paths. This makes the process of writting exercises extremely painful and error prone manually formatting and not getting any editor help.
Ideally exercises should live in /src/main/scala as any other source or a location where Ensime and IDEA are able to treat them as any ordinary scala source.

Let's give this priority after resolving the issues with #259. @dialelo and myself are writing exercises and would love to have this ASAP.

### PR DESCRIPTION
**Pull request by andyscott**
This changes the exercise source path to `src/main/scala` instead of `src/main/exercises` by removing the intermediate compilation phase in the sbt plugin. Some minor cleanup can probably be done with how dependencies are mapped.

Closes #303.

### CODE REVIEW

**Comment by dialelo** [comment]
I'm seeing a few compilation errors in the `content` project, see [this line in the CI build output](https://travis-ci.org/scala-exercises/scala-exercises/builds/117635039#L7141). Note that the `content` project now depends on Shapeless for generating test cases for the exercises.

**Comment by juanpedromoreno** [comment]
Since these issues have been resolved at https://github.com/scala-exercises/scala-exercises/compare/rr-shapeless-hlist-exercises and right now it's working fine in that branch. Let's move these compilation improvements in a different PR once they're merged. @andyscott Does it make sense to you if we close this PR?

**Comment by andyscott** [comment]
What about leaving this PR open and rebasing/merging once the other changes are integrated?

**Comment by andyscott** [comment]
Pushed some changes to fix the tests. It was a classpath issue-- so hopefully Travis passes now.

**Comment by andyscott** [comment]
Heads up. The builds are timing out on Travis right now. Not sure what's going on.

**Comment by andyscott** [comment]
@raulraja @rafaparadela please review.

I can rebase/fixup the changes from the `rr-shapeless-hlist-exercises` branch to work on top of this, when the time comes.

**Comment by juanpedromoreno** [comment]
LGTM

**Comment by raulraja** [comment]
LGTM! The shapeless exercises are a work in progress and we can try to merge what's there now. Let's get all these changes to master. New contributors are starting to experience the issue with the imports and what is on my branch already makes wrtting exercises an experience a lot more enjoyable. LGTM!

**Pull request merged**
