### PR TITLE
Jorgegalindo se 506 add new call to action

### PR DESCRIPTION
**Pull request by jorgegalindocruces**
Please @raulraja, can you review it?

I think that that design its pretty awesome to do a call to action to new committers and contributors :-)

### CODE REVIEW

**Comment by jorgegalindocruces** [comment]
screen shot 2016-07-12 at 21 46 53

FYI -> This is a screenshot of the result

**Comment by raulraja** [comment]
Looks great! @maureenelsberry can you do a quick Lang pass before publishing this?

**Comment by MaureenElsberry** [comment]
@raulraja @jorgegalindocruces  - I would suggest one of these two options:

Adding an exercise pack for a new library is easy! Help us make this platform bigger by adding your contribution. 

Adding exercises for a new library is easy! Help us make this platform bigger by collaborating with us! 

Is the "How can I help" linked to the instructions for adding a new library? If so, "How Can I Help" seems a little odd, because based on the above wording, we know they can help by adding exercises. I might suggest using something like "Find out how"   - if you prefer leaving the how can i help that is fine, I just think another option might be more fitting.

**Comment by raulraja** [comment]
The main message is to invite library authors to add exercises for their
library to Scala Exercises. By doing so they will not only help their users
learn to use their library better and faster but also by having it in Scala
Exercises they will get new users that will discover their library trough
Scala Exercises. If we can convey that message in a couple of sentences by
all means feel free to recommend complete new phrases and we will use
yours. I think @jorgegalindocruces and I are in agreement that you can
phrase it better than any of us . :)

**Comment by jorgegalindocruces** [comment]
Just added the comments of @MaureenElsberry. Thanks for everything!

@raulraja please, can you check it?

**Comment by raulraja** [comment]
@jorgegalindocruces That message does not invite library authors to add their library. Contribution is ambiguous and we have many other means to contribute such as fixing exercises, docs, etc. I asked @MaureenElsberry to provide a complete new phrase that highlights the fact that we are asking Library authors to add their library to Scala Exercises.

**Comment by MaureenElsberry** [comment]
Sorry, @raulraja I guess I wasn't clear that you wanted that changed last night. These are in no means that great, but here is a list of a bunch of random examples. If you want something a little more refined let me know. 

Below are some options directed towards Scala library authors:

-Do you have a Scala library? Add exercises to help people learn your toolset the easy way. 
-Help us expand this platform by adding an exercise track for your library. It's easy!   
-Help people learn to use your library by adding a specific exercise track to this platform. It's easy!
-Let's grow this project! Help us by adding an exercise track for your library, it's easy!
-Want people to learn how to use your library? Adding exercises for your project is easy.
-Adding exercises for your library is easy, help people learn to use the tools you've created.

I can make up more if requested....

**Comment by raulraja** [comment]
Those all look great. I like...
Want people to learn how to use your library? Adding exercises for your
project is easy.

**Comment by jorgegalindocruces** [comment]
Add that text into the box.

Anyone can give me a LGTM? cc @raulraja @juanpedromoreno @jdesiloniz @franciscodr

**Comment by franciscodr** [comment]
LGTM

**Pull request merged**
