### PR TITLE
Adds Monocle library

### LINKED ISSUE #620: Monocle Exercises
Related to https://github.com/julien-truffaut/Monocle/issues/380

### PR DESCRIPTION
**Pull request by valydia**
Fixes #620

### CODE REVIEW

**Comment by valydia** [comment]
@julien-truffault could you please provide a svg for the monocle logo? I think it should come under this folder https://github.com/scala-exercises/scala-exercises/tree/master/server/public/images.

**Comment by julien-truffaut** [comment]
@valydia do you need a white logo for https://www.scala-exercises.org/

**Comment by valydia** [comment]
Yes please, thanks!

**Comment by julien-truffaut** [comment]
@valydia here you are https://github.com/julien-truffaut/Monocle/blob/master/image/white_icons/logo_without_hat.svg

**Comment by valydia** [comment]
Thanks @julien-truffaut, but unfortunately this svg image looks to be too big! Looking at the other exercises project, the dimension should be 32x 32 
``` xml
<svg width="32px" height="32px" viewBox="0 0 32 32" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```
Do you have a way to easy to resize it? If not, I can look into it (even though my designer skills are really poor 😜 )? cheers

**Comment by julien-truffaut** [comment]
hum I thought the principle of svg is that you can resize the image as you wish

**Comment by valydia** [comment]
Apparently, it's not as straight forward as this, I've made some tests modifiying the svg file itself, or using some design software. It looks like the best tool to work with it is Sketch, I've made some promising progress with it!

**Comment by julien-truffaut** [comment]
Sorry @valydia, if you want I can have a look this weekend but I also don't really have any experience with this :)

**Comment by juanpedromoreno** [comment]
Solved in https://github.com/scala-exercises/scala-exercises/pull/630

Thanks anyway!

**Comment by julien-truffaut** [comment]
Thanks!

**Pull request closed without merging**
