### PR TITLE
Make Compile configuration behave

### PR DESCRIPTION
**Pull request by andyscott**
We want the standard Compile configuration to behave "normally" so that plugins like Scalariform will interface nicely with the exercise compiler.

I've rearranged the various tasks/configurations in the plugin so it behaves that way.

### CODE REVIEW

**Comment by andyscott** [comment]
@scala-exercises/core-mergers give this a whirl

**Comment by raulraja** [comment]
LGTM,! Thanks for taking care of this!

**Comment by dialelo** [comment]
`content` no longer compiles for me with these changes, here's the error messages I get from the compiler:

```
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:2: object fortysevendeg is not a member of package com
[error]   import com.fortysevendeg.exercises.Exercise
[error]              ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:4: object fortysevendeg is not a member of package com
[error]   import com.fortysevendeg.exercises.Library
[error]              ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:6: object fortysevendeg is not a member of package com
[error]   import com.fortysevendeg.exercises.Section
[error]              ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:8: not found: type Library
[error]   object Library_cats$1 extends Library {
[error]                                 ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:15: not found: type Section
[error]   object Section_monoid$1 extends Section {
[error]                                   ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:58: not found: type Section
[error]   object Section_functor$1 extends Section {
[error]                                    ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:101: not found: type Section
[error]   object Section_apply$1 extends Section {
[error]                                  ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:171: not found: type Section
[error]   object Section_applicative$1 extends Section {
[error]                                        ^
[error] /home/dialelo/47/scala-exercises/site/content/target/scala-2.11/src_managed/main/defaultLib/Library_cats$1.scala:205: not found: type Section
[error]   object Section_monad$1 extends Section {
```

**Comment by dialelo** [comment]
Nevermind, is working after an `sbt clean`.

**Pull request merged**
